file_format: "1"
id: klotz
name: Klotz
type: shield
url: https://github.com/GEIGEIGEIST/KLOTZ
requires: [pro_micro]
exposes: []
features:
  - keys
  - encoder
siblings:
  - klotz_left
  - klotz_right
